openapi: 3.2.0
info:
  title: Assembly Users API
  description: Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
  version: '2.3'
  contact:
    email: support@assemblypayments.com
    url: http://docs.assemblypayments.com/
servers:
- url: https://test.api.promisepay.com
  description: Pre-live environment
- url: https://secure.api.promisepay.com
  description: Production environment
- url: https://au-0000.sandbox.auth.assemblypay.com
  description: Pre-Live (Sandbox) Auth issuing server and API
- url: https://au-0000.auth.assemblypay.com
  description: Production Auth issuing server and API
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/AssemblyPlatforms/assembly-api/2.3
security:
- oAuth2ClientCredentials: []
tags:
- name: Users
paths:
  /users/{id}/bpay_accounts:
    get:
      tags:
      - Users
      summary: List User's BPay Accounts
      description: List the **BPay Accounts** the **User** is associated with using a given `:id`.
      operationId: listUserBPayAccounts
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: 901d8cd0-6af3-0138-967d-0a58a9feac04
        example: 901d8cd0-6af3-0138-967d-0a58a9feac04
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_bpay_accounts'
              examples:
                response:
                  value:
                    bpay_accounts:
                    - id: b0980390-ac5b-0138-8b2e-0a58a9feac03
                      active: true
                      created_at: '2020-07-20 02:07:33.583000+00:00'
                      updated_at: '2020-07-20 02:07:33.583000+00:00'
                      bpay_details:
                        biller_name: APIBCD AV4
                        account_name: Test Biller
                        biller_code: '93815'
                        crn: '613295205'
                      currency: AUD
                      verification_status: verified
                      links:
                        self: /bpay_accounts/b0980390-ac5b-0138-8b2e-0a58a9feac03
                        users: /bpay_accounts/b0980390-ac5b-0138-8b2e-0a58a9feac03/users
                    meta:
                      limit: 10
                      offset: 0
                      total: 1
                    links:
                      self: /users/901d8cd0-6af3-0138-967d-0a58a9feac04/bpay_accounts
  /users/{id}/card_accounts:
    get:
      tags:
      - Users
      summary: Show User Card Account
      description: Show the user's active card account using a given `:id`.
      operationId: showUserCardAccount
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: buyer-71439598
        example: buyer-71439598
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/card_account'
              examples:
                response:
                  value:
                    card_accounts:
                      active: true
                      created_at: '2020-05-06T01:38:29.022Z'
                      updated_at: '2020-05-06T01:38:29.022Z'
                      id: 35977230-7168-0138-0a1d-0a58a9feac07
                      verification_status: not_verified
                      cvv_verified: true
                      currency: AUD
                      card:
                        type: visa
                        full_name: Neol Test
                        number: XXXX-XXXX-XXXX-1111
                        expiry_month: '7'
                        expiry_year: '2021'
                      links:
                        self: /users/buyer-71439598/card_accounts
                        users: /card_accounts/35977230-7168-0138-0a1d-0a58a9feac07/users
  /users/{id}:
    get:
      tags:
      - Users
      summary: Show User
      description: Show details of a specific User using a given `:id`.
      operationId: showUser
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: string
          default: buyer-1556506027
        example: buyer-1556506027
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_user'
              examples:
                response:
                  value:
                    users:
                      created_at: '2019-04-29T02:47:08.348Z'
                      updated_at: '2019-04-29T02:47:08.348Z'
                      full_name: Neol1556506027 Calangi
                      email: neol.calangi+buyer1556506027@promisepay.com
                      mobile: '+21556506027'
                      phone: null
                      logo_url: null
                      color_1: null
                      color_2: null
                      first_name: Neol1556506027
                      last_name: Calangi
                      id: buyer-1556506027
                      custom_descriptor: null
                      location: AUS
                      verification_state: pending
                      held_state: false
                      roles:
                      - customer
                      dob: encrypted
                      government_number: null
                      drivers_license: null
                      flags: {}
                      related:
                        addresses: 00eb5be0-4c57-0137-ad3d-0242ac110002
                      links:
                        self: /users/buyer-1556506027
                        items: /users/buyer-1556506027/items
                        card_accounts: /users/buyer-1556506027/card_accounts
                        paypal_accounts: /users/buyer-1556506027/paypal_accounts
                        payid_accounts: /users/buyer-1556506027/payid_accounts
                        bank_accounts: /users/buyer-1556506027/bank_accounts
                        wallet_accounts: /users/buyer-1556506027/wallet_accounts
    patch:
      tags:
      - Users
      summary: Update User
      description: Update an existing **User's** attributes using a given `:id`.
      operationId: updateUser
      parameters:
      - name: id
        in: path
        description: Unique ID that can be generated by the platform. Cannot contain '.' character.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: buyer-1556506027
        example: buyer-1556506027
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_user_requestBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_user'
              examples:
                response:
                  value:
                    users:
                      created_at: '2019-04-29T02:47:08.348Z'
                      updated_at: '2019-04-29T02:47:08.348Z'
                      full_name: Neol1556506027 Calangi
                      email: neol.calangi+buyer1556506027@promisepay.com
                      mobile: '+21556506027'
                      phone: null
                      logo_url: null
                      color_1: null
                      color_2: null
                      first_name: Neol1556506027
                      last_name: Calangi
                      id: buyer-1556506027
                      custom_descriptor: null
                      location: AUS
                      verification_state: pending
                      held_state: false
                      roles:
                      - customer
                      dob: encrypted
                      government_number: null
                      drivers_license: null
                      flags: {}
                      related:
                        addresses: 00eb5be0-4c57-0137-ad3d-0242ac110002
                      links:
                        self: /charges/4d7d73f5-c7f0-477d-aff8-7570d2c7e7d9/buyers
                        items: /users/buyer-1556506027/items
                        card_accounts: /users/buyer-1556506027/card_accounts
                        paypal_accounts: /users/buyer-1556506027/paypal_accounts
                        payid_accounts: /users/buyer-1556506027/payid_accounts
                        bank_accounts: /users/buyer-1556506027/bank_accounts
                        wallet_accounts: /users/buyer-1556506027/wallet_accounts
  /users/{id}/identity_verified:
    patch:
      tags:
      - Users
      summary: Verify User (Prelive Only)
      description: 'Sets a user''s verification state to `approved` on pre-live given the **User** `:id`. Ensure that a **User** has the required user verification information before using this call, otherwise the call will fail. **Note**: This API call will only work in our pre-live environment. The user verification workflow holds for all users in production.

        '
      operationId: verifyUser
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: buyer-1556506027
        example: buyer-1556506027
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_user'
              examples:
                response:
                  value:
                    users:
                      created_at: '2019-04-29T02:47:08.348Z'
                      updated_at: '2019-04-29T02:47:08.348Z'
                      full_name: Neol1556506027 Calangi
                      email: neol.calangi+buyer1556506027@promisepay.com
                      mobile: '+21556506027'
                      phone: null
                      logo_url: null
                      color_1: null
                      color_2: null
                      first_name: Neol1556506027
                      last_name: Calangi
                      id: buyer-1556506027
                      custom_descriptor: null
                      location: AUS
                      verification_state: pending
                      held_state: false
                      roles:
                      - customer
                      dob: encrypted
                      government_number: null
                      drivers_license: null
                      flags: {}
                      related:
                        addresses: 00eb5be0-4c57-0137-ad3d-0242ac110002
                      links:
                        self: /charges/4d7d73f5-c7f0-477d-aff8-7570d2c7e7d9/buyers
                        items: /users/buyer-1556506027/items
                        card_accounts: /users/buyer-1556506027/card_accounts
                        paypal_accounts: /users/buyer-1556506027/paypal_accounts
                        payid_accounts: /users/buyer-1556506027/payid_accounts
                        bank_accounts: /users/buyer-1556506027/bank_accounts
                        wallet_accounts: /users/buyer-1556506027/wallet_accounts
  /users/{id}/bank_accounts:
    get:
      tags:
      - Users
      summary: Show User Bank Account
      description: Shows the user's active bank account using a given `:id`.
      operationId: showUserBankAccount
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: 46deb476-c1a6-41eb-8eb7-26a695bbe5bc
        example: 46deb476-c1a6-41eb-8eb7-26a695bbe5bc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bank_account_au'
              examples:
                response:
                  value:
                    bank_accounts:
                      id: 46deb476-c1a6-41eb-8eb7-26a695bbe5bc
                      created_at: '2016-04-12T09:20:38.540Z'
                      updated_at: '2016-04-12T09:20:38.540Z'
                      active: true
                      verification_status: not_verified
                      currency: AUD
                      bank:
                        bank_name: Bank of Australia
                        country: AUS
                        account_name: Samuel Seller
                        routing_number: XXXXX3
                        account_number: XXX234
                        holder_type: personal
                        account_type: checking
                        direct_debit_authority_status: null
                      links:
                        self: /users/46deb476-c1a6-41eb-8eb7-26a695bbe5bc/bank_accounts
                        users: /bank_accounts/46deb476-c1a6-41eb-8eb7-26a695bbe5bc/users
                        direct_debit_authorities: /bank_accounts/46deb476-c1a6-41eb-8eb7-26a695bbe5bc/direct_debit_authorities
  /users/{id}/disbursement_account:
    patch:
      tags:
      - Users
      summary: Set User Disbursement Account
      description: Set the **User's Disbursement Account** using a given **User** `:id` and a **Bank Account** `:account_id`.
      operationId: setUserDisbursementAccount
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: string
          default: Seller_1234
        example: Seller_1234
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bank_account_id_requestBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_user'
              examples:
                response:
                  value:
                    users:
                      created_at: '2020-04-03T07:59:00.379Z'
                      updated_at: '2020-04-03T07:59:00.379Z'
                      id: Seller_1234
                      full_name: Samuel Seller
                      email: sam@example.com
                      mobile: 69543131
                      phone: null
                      logo_url: null
                      color_1: null
                      color_2: null
                      first_name: Samuel
                      last_name: Seller
                      custom_descriptor: Sam Garden Jobs
                      location: AUS
                      verification_state: pending
                      held_state: false
                      roles:
                      - customer
                      dob: encrypted
                      government_number: encrypted
                      drivers_license: null
                      flags: {}
                      related:
                        addresses: 11111111-2222-3333-4444-55555555555,
                      links:
                        self: /bank_accounts/901d8cd0-6af3-0138-967d-0a58a9feac04/users
                        items: /users/e6bc0480-57ae-0138-c46e-0a58a9feac03/items
                        card_accounts: /users/e6bc0480-57ae-0138-c46e-0a58a9feac03/card_accounts
                        paypal_accounts: /users/e6bc0480-57ae-0138-c46e-0a58a9feac03/paypal_accounts
                        payid_accounts: /users/e6bc0480-57ae-0138-c46e-0a58a9feac03/payid_accounts
                        bank_accounts: /users/e6bc0480-57ae-0138-c46e-0a58a9feac03/bank_accounts
                        wallet_accounts: /users/e6bc0480-57ae-0138-c46e-0a58a9feac03/wallet_accounts
  /users:
    get:
      tags:
      - Users
      summary: List Users
      description: Retrieve an ordered and paginated list of existing **Users**.
      operationId: listUsers
      parameters:
      - $ref: '#/components/parameters/limitParam'
      - $ref: '#/components/parameters/offsetParam'
      - name: search
        in: query
        description: A text value to be used for searching users
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
              examples:
                response:
                  value:
                    users:
                    - id: seller-71460518
                      full_name: Assembly seller71460518
                      first_name: Assembly
                      last_name: seller71460518
                      created_at: '2020-05-06T07:26:59.479Z'
                      updated_at: '2020-05-06T07:26:59.479Z'
                      email: neol_seller71460518@assemblypayments.com
                      mobile: '+1588750018'
                      phone: null
                      location: N/A
                      links:
                        self: /users/seller-71460518
                        items: /users/seller-71460518/items
                        card_accounts: /users/seller-71460518/card_accounts
                        paypal_accounts: /users/seller-71460518/paypal_accounts
                        bank_accounts: /users/seller-71460518/bank_accounts
                        wallet_accounts: /users/seller-71460518/wallet_accounts
                    - id: buyer-71439598
                      full_name: Buyer
                      first_name: Buyer
                      last_name: ''
                      created_at: '2020-05-06T01:38:19.116Z'
                      updated_at: '2020-05-06T02:03:25.941Z'
                      email: assemblybuyer71439598@assemblypayments.com
                      mobile: null
                      phone: null
                      location: N/A
                      links:
                        self: /users/buyer-71439598
                        items: /users/buyer-71439598/items
                        card_accounts: /users/buyer-71439598/card_accounts
                        paypal_accounts: /users/buyer-71439598/paypal_accounts
                        bank_accounts: /users/buyer-71439598/bank_accounts
                        wallet_accounts: /users/buyer-71439598/wallet_accounts
                    meta:
                      limit: 2
                      offset: 0
                      total: 16
                    links:
                      self: /users
    post:
      tags:
      - Users
      summary: Create User
      description: 'Create a **User** that can be associated with **Items** as either a buyer or a seller. **Users** can''t be both the buyer and seller for the same **Item**. You can also use this endpoint to create a **company** for the user. To create a company for the user, you need to send company parameters in the same request. **Note**: Some parameters are required for user verification. See our guide on [Onboarding a Payout User/Seller](https://developer.hellozai.com/docs/onboarding-a-pay-out-user) for more information.

        '
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_requestBody'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_user'
              examples:
                response:
                  value:
                    users:
                      created_at: '2019-04-29T02:47:08.348Z'
                      updated_at: '2019-04-29T02:47:08.348Z'
                      full_name: Neol1556506027 Calangi
                      email: neol.calangi+buyer1556506027@promisepay.com
                      mobile: '+21556506027'
                      phone: null
                      logo_url: null
                      color_1: null
                      color_2: null
                      first_name: Neol1556506027
                      last_name: Calangi
                      id: buyer-1556506027
                      custom_descriptor: null
                      location: AUS
                      verification_state: pending
                      held_state: false
                      roles:
                      - customer
                      dob: encrypted
                      government_number: null
                      drivers_license: null
                      flags: {}
                      related:
                        addresses: 00eb5be0-4c57-0137-ad3d-0242ac110002
                      links:
                        self: /charges/4d7d73f5-c7f0-477d-aff8-7570d2c7e7d9/buyers
                        items: /users/buyer-1556506027/items
                        card_accounts: /users/buyer-1556506027/card_accounts
                        paypal_accounts: /users/buyer-1556506027/paypal_accounts
                        payid_accounts: /users/buyer-1556506027/payid_accounts
                        bank_accounts: /users/buyer-1556506027/bank_accounts
                        wallet_accounts: /users/buyer-1556506027/wallet_accounts
  /users/{id}/items:
    get:
      tags:
      - Users
      summary: List User Items
      description: Retrieve an ordered and paginated list of existing **Items** the **User** is associated with using a given `:id`.
      operationId: listUserItems
      parameters:
      - $ref: '#/components/parameters/offsetParam'
      - $ref: '#/components/parameters/limitParam'
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: test-user-1592459047-22
        example: test-user-1592459047-22
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/items'
              examples:
                response:
                  value:
                    items:
                    - id: 7139651-1-2046
                      name: Item 7139651-1-2046
                      description: Test Item 7139651-1-2046
                      created_at: '2020-05-05T12:26:50.782Z'
                      updated_at: '2020-05-05T12:31:03.654Z'
                      state: payment_deposited
                      payment_type_id: 2
                      status: 22200
                      amount: 109
                      deposit_reference: '100014012501482'
                      buyer_name: Buyer Last Name
                      buyer_country: AUS
                      buyer_email: assemblybuyer71391895@assemblypayments.com
                      seller_name: Assembly seller71391950
                      seller_country: AUS
                      seller_email: neol_seller71391950@assemblypayments.com
                      tds_check_state: NA
                      currency: AUD
                      links:
                        self: /items/7139651-1-2046
                        buyers: /items/7139651-1-2046/buyers
                        sellers: /items/7139651-1-2046/sellers
                        status: /items/7139651-1-2046/status
                        fees: /items/7139651-1-2046/fees
                        transactions: /items/7139651-1-2046/transactions
                        batch_transactions: /items/7139651-1-2046/batch_transactions
                        wire_details: /items/7139651-1-2046/wire_details
                        bpay_details: /items/7139651-1-2046/bpay_details
                    links:
                      self: /items
                    meta:
                      limit: 10
                      offset: 0
                      total: 1
  /users/{id}/wallet_accounts:
    get:
      tags:
      - Users
      summary: Show User Wallet Account
      description: Show the **User's Wallet Account** using a given `:id`.
      operationId: showUserWalletAccounts
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: aed45af0-6f63-0138-901c-0a58a9feac03
        example: aed45af0-6f63-0138-901c-0a58a9feac03
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wallet_account'
              examples:
                response:
                  value:
                    wallet_accounts:
                      id: 5c1c6b10-4c56-0137-8cd7-0242ac110002
                      active: true
                      created_at: '2019-04-29T02:42:31.536Z'
                      updated_at: '2020-05-03T12:01:02.254Z'
                      balance: 663337
                      currency: AUD
                      links:
                        self: /transactions/aed45af0-6f63-0138-901c-0a58a9feac03/wallet_accounts
                        users: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/users
                        batch_transactions: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/batch_transactions
                        transactions: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/transactions
                        bpay_details: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/bpay_details
                        npp_details: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/npp_details
                        virtual_accounts: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/virtual_accounts
components:
  schemas:
    single_user:
      type: object
      properties:
        users:
          $ref: '#/components/schemas/user'
    bank_account_id_requestBody:
      type: object
      required:
      - account_id
      properties:
        account_id:
          description: Account ID (Bank account)
          type: string
          example: 901d8cd0-6af3-0138-967d-0a58a9feac04
          default: 901d8cd0-6af3-0138-967d-0a58a9feac04
    bank_account_au:
      type: object
      properties:
        bank_accounts:
          type: object
          properties:
            active:
              type: boolean
              example: true
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
            id:
              type: string
              format: uuid
              example: 46deb476-c1a6-41eb-8eb7-26a695bbe5bc
            currency:
              type: string
              example: AUD
            verification_status:
              type: string
              enum:
              - not_verified
              - in_progress
              - processed
              example: not_verified
            verification:
              type: object
              properties:
                verified_at:
                  type: string
                  format: date-time
                verification_method:
                  type: string
                  enum:
                  - COP
                result:
                  type: object
                  properties:
                    match_result:
                      type: string
                      enum:
                      - MTCH
                      - MTCO
                      - CMTC
                      - WMTC
                      - NMTC
                      - NMTO
                      - NINF
                      - NFND
                      - CLSD
            bank:
              type: object
              properties:
                bank_name:
                  type: string
                  example: Bank of Australia
                country:
                  type: string
                  example: AUS
                account_name:
                  type: string
                  example: Samuel Seller
                routing_number:
                  type: string
                  example: XXXXX3
                account_number:
                  type: string
                  example: XXX234
                holder_type:
                  type: string
                  enum:
                  - personal
                  - business
                  example: personal
                account_type:
                  type: string
                  enum:
                  - savings
                  - checking
                  example: checking
                direct_debit_authority_status:
                  type: string
                  readOnly: true
                  enum:
                  - 'null'
                  - approved
                  example: approved
            links:
              type: object
              properties:
                self:
                  type: string
                users:
                  type: string
                direct_debit_authorities:
                  type: string
    item:
      type: object
      required:
      - id
      - name
      - amount
      - payment_type
      - buyer_id
      - seller_id
      properties:
        id:
          type: string
          example: 7190770-1-2908
        name:
          type: string
          example: 'Item #001'
        description:
          type: string
          example: My first Item.
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        state:
          type: string
          enum:
          - pending
          - payment_required
          - wire_pending
          - payment_pending
          - payment_held
          - payment_authorized
          - void_pending
          - voided
          - fraud_hold
          - payment_deposited
          - work_completed
          - problem_flagged
          - problem_resolve_requested
          - problem_escalated
          - completed
          - cancelled
          - refunded
          - refund_pending
          - refund_flagged
          - off_platform_refunded
          - partial_completed
          - partial_paid
          - off_platform_chargedback
          example: pending
        status:
          type: integer
          enum:
          - 22000
          - 22100
          - 22110
          - 22150
          - 22175
          - 22180
          - 22185
          - 22195
          - 22190
          - 22200
          - 22300
          - 22400
          - 22410
          - 22420
          - 22500
          - 22575
          - 22600
          - 22610
          - 22650
          - 22670
          - 22700
          - 22800
          - 22680
          example: 22000
        amount:
          type: integer
          example: 20000
        payment_type_id:
          type: integer
          example: 2
        currency:
          type: string
          example: AUD
        buyer_name:
          type: string
          example: Sample Buyer
        buyer_email:
          type: string
          format: email
          example: sample.buyer@assemblypayments.com
        buyer_country:
          type: string
          example: AUS
        seller_name:
          type: string
          example: Sample Seller
        seller_email:
          type: string
          format: email
          example: sample.seller@assemblypayments.com
        seller_country:
          type: string
          format: email
          example: AUS
        tds_check_state:
          type: string
          format: email
          example: NA
        batch_state:
          type: string
          example: null
        invoice_url:
          type: string
          example: null
        payout_descriptor:
          type: string
          example: null
        remaining_amount:
          type: integer
          example: 0
        requested_release_amount:
          type: integer
          example: 0
        custom_descriptor:
          type: string
          example: null
        net_amount:
          type: integer
          example: 20000
        chargedback_amount:
          type: integer
          example: 0
        refunded_amount:
          type: integer
          example: 0
        released_amount:
          type: integer
          example: 0
        buyer_fees:
          type: integer
          example: 0
        seller_fees:
          type: integer
          example: 400
        credit_card_fee:
          type: integer
          example: 0
        paypal_fee:
          type: integer
          example: 0
        seller_url:
          type: string
        buyer_url:
          type: string
        direct_debit_fee:
          type: integer
          example: 0
        due_date:
          type:
          - string
          - 'null'
          format: date
        pending_release_amount:
          type: integer
          example: 0
        dynamic_descriptor:
          type: string
          example: null
        deposit_reference:
          type: string
          example: 100014013961629
        promisepay_fee:
          type: integer
          example: 350
        total_outstanding:
          type: integer
          example: 20000
        total_amount:
          type: integer
          example: 20000
        payment_method:
          type: string
          example: pending
        payment_credit_card_enabled:
          type: boolean
          example: true
        payment_direct_debit_enabled:
          type: boolean
          example: true
        related:
          type: object
          properties:
            buyers:
              type: string
              example: 064d6800-fff3-11e5-86aa-5e5517507c66
            sellers:
              type: string
              example: 5830def0-ffe8-11e5-86aa-5e5517507c66
        links:
          type: object
          properties:
            self:
              type: string
            buyers:
              type: string
            sellers:
              type: string
            status:
              type: string
            fees:
              type: string
            transactions:
              type: string
            batch_transactions:
              type: string
            wire_details:
              type: string
            bpay_details:
              type: string
            tds_checks:
              type: string
    user_requestBody:
      type: object
      required:
      - id
      - first_name
      - last_name
      - email
      - country
      properties:
        id:
          description: Unique ID that can be generated by the platform. Cannot contain '.'  character. Contact Assembly support if you want user IDs to be generated automatically.
          type: string
          example: buyer-1556506027
          default: buyer-1556506027
        first_name:
          description: First name of the user
          type: string
          example: Neol1556506027
          default: Neol1556506027
        last_name:
          description: Last name of the user
          type: string
          example: Calangi
          default: Calangi
        email:
          description: Email of the user. Unique to platform.
          type: string
          example: neol.calangi+buyer1556506027@promisepay.com
          default: neol.calangi+buyer1556506027@promisepay.com
        mobile:
          description: International number format. Include '+' and no spaces.
          type: string
          example: '+21556506027'
        address_line1:
          description: First line of the user address
          type: string
          example: ''
        address_line2:
          description: Second line of the user address
          type: string
          example: ''
        state:
          description: State section of the user address
          type: string
          example: ''
        city:
          description: City section of the user address
          type: string
          example: ''
        zip:
          description: Postcode
          type: string
          example: ''
        country:
          description: '[ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Officially_assigned_code_elements) country code (3 char)'
          type: string
          example: AUS
          default: AUS
        dob:
          description: Date of Birth (DD/MM/YYYY).
          type: string
          example: null
        government_number:
          description: Generic parameter to capture important user verification data. eg. SSN for US users, TFN for AU users.
          type: string
          example: ''
        drivers_license_number:
          description: Driving license number of the user
          type: string
          example: ''
        drivers_license_state:
          description: State section of the user's driving license
          type: string
          example: ''
        ip_address:
          description: IP address
          type: string
          example: ''
        logo_url:
          description: URL link to the logo
          type: string
          example: ''
        color_1:
          description: Color code number 1
          type: string
          example: ''
        color_2:
          description: Color code number 2
          type: string
          example: ''
        custom_descriptor:
          description: When custom_descriptors are enabled, this is the information to appear on bundle direct debit statements (which show the buyer's custom_descriptor) as well as international wire payout, direct credit and PayPal payout statements (which show the seller's custom_descriptor)
          type: string
          example: ''
        authorized_signer_title:
          description: '‘Authorised Signer Title’, which refers to the role / job title (e.g. Director or General Manager) for the individual User, who is authorised to sign contracts on behalf of the business entity / Merchant User. (Note: information required for AMEX Merchants)'
          type: string
          example: Director
        company:
          required:
          - country
          - legal_name
          - name
          - tax_number
          - business_email
          type: object
          description: This is an optional field and if provided, the company will be created for the user.
          properties:
            name:
              type: string
              description: Company name
              example: ABC
              default: ABC
            legal_name:
              type: string
              description: Company legal name
              example: ABC Pty Ltd
              default: ABC Pty Ltd
            tax_number:
              type: string
              description: ABN / TFN
              example: '123456789'
              default: '123456789'
            business_email:
              description: The business email address associated with the user or business.
              type: string
              example: test@sample.com
            charge_tax:
              type:
              - boolean
              - 'null'
              description: Charge GST? Use the value True to charge GST. Use False to not charge GST.
              example: false
            address_line1:
              type: string
              description: Address line 1
              example: Collins
            address_line2:
              type: string
              description: Address line 2
              example: ''
            city:
              type: string
              description: City
              example: Melbourne
            state:
              type: string
              description: State
              example: VIC
            zip:
              type: string
              description: Zip
              example: '3000'
            country:
              type: string
              description: 2 or 3 letter country code. (e.g. AUS)
              example: AUS
              default: AUS
            phone:
              type: string
              description: Company phone number
              example: ''
              default: ''
    users:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/user'
    user:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        full_name:
          type: string
          example: Samuel Seller
        email:
          type: string
          format: email
          example: samuel.seller@assemblypayments.com
        mobile:
          type: string
          example: 61491570156
        phone:
          type: string
        logo_url:
          type: string
        color_1:
          type: string
        color_2:
          type: string
        first_name:
          type: string
          example: Samuel
        last_name:
          type: string
          example: Seller
        id:
          type: string
          example: Seller_1234
        custom_descriptor:
          type: string
        location:
          type: string
          example: AUS
        verification_status:
          type: string
          example: pending
        held_state:
          type: boolean
          example: false
        roles:
          type: array
          items:
            type: string
            example: customer
        dob:
          type: string
          example: encrypted
        government_number:
          type: string
          example: encrypted
        drivers_license:
          type: string
        flags:
          type: object
        related:
          type: object
          properties:
            addresses:
              type: string
              example: fe602dcf-4175-4f88-b5be-3beb04092dcd
        links:
          type: object
          properties:
            self:
              type: string
            items:
              type: string
            card_accounts:
              type: string
            paypal_accounts:
              type: string
            payid_accounts:
              type: string
            bpay_accounts:
              type: string
            bank_accounts:
              type: string
            wallet_accounts:
              type: string
    list_bpay_accounts:
      properties:
        bpay_accounts:
          type: array
          items:
            type: object
            properties:
              active:
                type: boolean
                example: true
              created_at:
                type: string
                format: date-time
              updated_at:
                type: string
                format: date-time
              id:
                type: string
                format: uuid
                example: 46deb476-c1a6-41eb-8eb7-26a695bbe5bc
              currency:
                type: string
                example: AUD
              verification_status:
                type: string
                enum:
                - verified
                - not_verified
                example: not_verified
              bpay_details:
                type: object
                properties:
                  account_name:
                    type: string
                    example: My biller 123
                    description: Name assigned by the platform/marketplace to identify the account (similar to a nickname)
                  biller_code:
                    type: integer
                    example: 123456
                  biller_name:
                    type: string
                    description: Name of the biller as registered in BPay
                    example: ABC Water
                  crn:
                    type: integer
                    example: 987654321
              links:
                type: object
                properties:
                  self:
                    type: string
                  users:
                    type: string
        links:
          type: object
          properties:
            self:
              type: string
        meta:
          type: object
          properties:
            limit:
              type: integer
            offset:
              type: integer
            total:
              type: integer
    items:
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/item'
        links:
          type: object
          properties:
            self:
              type: string
        meta:
          type: object
          properties:
            limit:
              type: integer
            offset:
              type: integer
            total:
              type: integer
    card_account:
      type: object
      properties:
        card_accounts:
          type: object
          properties:
            active:
              type: boolean
              example: true
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
            id:
              type: string
              format: uuid
              example: 46deb476-c1a6-41eb-8eb7-26a695bbe5bc
            currency:
              type: string
              example: AUD
            cvv_verified:
              type: boolean
              example: true
            verification_status:
              type: string
              enum:
              - verified
              - not_verified
              example: not_verified
            card:
              type: object
              readOnly: true
              properties:
                type:
                  type: string
                  example: visa
                full_name:
                  type: string
                  example: Bella Buyer
                number:
                  type: string
                  example: XXXX-XXXX-XXXX-1111
                expiry_month:
                  type: string
                  example: 10
                expiry_year:
                  type: string
                  example: 2020
            links:
              type: object
              properties:
                self:
                  type: string
                  example: /users/buyer-71439598/card_accounts
                users:
                  type: string
                  example: /card_accounts/35977230-7168-0138-0a1d-0a58a9feac07/users
    wallet_account:
      type: object
      properties:
        wallet_accounts:
          type: object
          properties:
            active:
              type: boolean
              example: true
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
            id:
              type: string
              format: uuid
              example: 46deb476-c1a6-41eb-8eb7-26a695bbe5bc
            currency:
              type: string
              example: AUD
            verification_status:
              type: string
              enum:
              - verified
              - not_verified
              example: not_verified
            balance:
              type: integer
            links:
              type: object
              properties:
                self:
                  type: object
                  example: /transactions/aed45af0-6f63-0138-901c-0a58a9feac03/wallet_accounts
                users:
                  type: object
                  example: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/users
                batch_transactions:
                  type: object
                  example: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/batch_transactions
                transactions:
                  type: object
                  example: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/transactions
                bpay_details:
                  type: object
                  example: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/bpay_details
                npp_details:
                  type: object
                  example: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/npp_details
                virtual_accounts:
                  type: object
                  example: /wallet_accounts/5c1c6b10-4c56-0137-8cd7-0242ac110002/virtual_accounts
    update_user_requestBody:
      type: object
      required:
      - first_name
      properties:
        first_name:
          description: First name of the user
          type: string
          example: Neol1556506027
          default: Neol1556506027
        last_name:
          description: Last name of the user
          type: string
          example: Calangi
        email:
          description: Email of the user. Unique to platform.
          type: string
          example: neol.calangi+buyer1556506027@promisepay.com
        mobile:
          description: International number format. Include '+' and no spaces.
          type: string
          example: '+21556506027'
        address_line1:
          description: First line of the user address
          type: string
          example: ''
        address_line2:
          description: Second line of the user address
          type: string
          example: ''
        state:
          description: State section of the user address
          type: string
          example: ''
        city:
          description: City section of the user address
          type: string
          example: ''
        zip:
          description: Postcode
          type: string
          example: ''
        country:
          description: '[ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Officially_assigned_code_elements) country code (3 char)'
          type: string
          example: AUS
        dob:
          description: Date of Birth (DD/MM/YYYY).
          type: string
          example: null
        government_number:
          description: Generic parameter to capture important user verification data. eg. SSN for US users, TFN for AU users.
          type: string
          example: ''
        drivers_license_number:
          description: Driving license number of the user
          type: string
          example: ''
        drivers_license_state:
          description: State section of the user's driving license
          type: string
          example: ''
        ip_address:
          description: IP address
          type: string
          example: ''
        logo_url:
          description: URL link to the logo
          type: string
          example: ''
        color_1:
          description: Color code number 1
          type: string
          example: ''
        color_2:
          description: Color code number 2
          type: string
          example: ''
        custom_descriptor:
          description: When custom_descriptors are enabled, this is the information to appear on bundle direct debit statements (which show the buyer's custom_descriptor) as well as international wire payout, direct credit and PayPal payout statements (which show the seller's custom_descriptor)
          type: string
          example: ''
        authorized_signer_title:
          description: '‘Authorised Signer Title’, which refers to the role / job title (e.g. Director or General Manager) for the individual User, who is authorised to sign contracts on behalf of the business entity / Merchant User. (Note: information required for AMEX Merchants)'
          type: string
          example: Director
  parameters:
    offsetParam:
      name: offset
      in: query
      description: Number of records to offset. Required for pagination.
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
    limitParam:
      name: limit
      in: query
      description: Number of records to retrieve. Up to 200.
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 200
        default: 10
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      description: Please refer to Authentication section within https://developer.assemblypayments.com/reference#authentication
      flows:
        clientCredentials:
          tokenUrl: https://au-0000.sandbox.auth.assemblypay.com/tokens
          scopes: {}
x-explorer-enabled: false
x-samples-languages:
- curl
- ruby
- php
- javascript
- csharp
- go
x-proxy-enabled: true
x-samples-enabled: true
